package org.omg.IOP;


/**
* org/omg/IOP/TransactionService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/8-2-build-windows-x64-cygwin-sans-NAS/jdk8u401/683/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Tuesday, December 19, 2023 12:39:32 PM UTC
*/

public interface TransactionService
{

  /**
     * Identifies a CDR encapsulation of the 
     * <code>CosTSInteroperation.PropogationContext</code> defined in 
     * <i>CORBAservices: Common Object Services Specifications.</i>
     */
  public static final int value = (int)(0L);
}
