package org.omg.PortableServer;


/**
* org/omg/PortableServer/ImplicitActivationPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/8-2-build-windows-x64-cygwin-sans-NAS/jdk8u401/683/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Tuesday, December 19, 2023 12:39:32 PM UTC
*/


/**
	 * This policy specifies whether implicit activation 
	 * of servants is supported in the created POA.
	 */
public interface ImplicitActivationPolicy extends ImplicitActivationPolicyOperations, org.omg.CORBA.Policy, org.omg.CORBA.portable.IDLEntity 
{
} // interface ImplicitActivationPolicy
